### ISSUE TITLE
Don't reverse the order of the dropdown options

### ISSUE THREAD

**Issue by finalight** [hoaphantn7604/react-native-element-dropdown#101]
![IMG_8026](https://user-images.githubusercontent.com/4475526/187101824-8e51b460-d727-44c7-ba58-196e1db66b0b.png)

is it possible not to reverse the order of the options whenver the options appears at the top of the dropdown select?

**Comment by hoaphantn7604** [comment]
hi @finalight ,
Refer this example:
```js
      <Dropdown
        ...
        flatListProps={{ inverted: false }}
      />
```

**Comment by Audrey-Ann** [comment]
@hoaphantn7604 I tried and it's not working unfortunately

**Comment by hoaphantn7604** [comment]
hi @Audrey-Ann,
Can you send a code example for me to support?

**Comment by hoaphantn7604** [comment]
hi @Audrey-Ann ,
dropdownPosition is "bottom" then  flatListProps={{ inverted: true }}.
dropdownPosition is "top" then  flatListProps={{ inverted: false }}.

**Comment by gpoontip** [comment]
@hoaphantn7604 
But when using `dropdownPosition="top"` and `flatListProps={{ inverted: false }}` with a large dataset (states for example) then it starts from the bottom (Wyoming). How can it work so that it starts at the top (Alabama)?

If I preselect Alabama and use the auto scroll feature there's a 1 second delay before it scrolls to the top.

Is there a better way?

**Comment by hoaphantn7604** [comment]
hi @all,
Please install version 2.7.0. Use prop inverted set is "false".
```js
   <Dropdown 
      {...}
      inverted={false}
   />
```
